# Generated by Django 2.0.2 on 2019-01-09 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=20, null=True)),
                ('recipient_addr', models.CharField(max_length=50, null=True)),
                ('zip', models.CharField(max_length=10, null=True)),
                ('phone_number', models.IntegerField(null=True)),
                ('cell_phone', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'addr',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20, null=True)),
                ('book_name', models.CharField(max_length=20, null=True)),
                ('summary', models.CharField(max_length=200, null=True)),
                ('custom_core', models.IntegerField(null=True)),
                ('inventory', models.IntegerField(null=True)),
                ('sales', models.IntegerField(null=True)),
                ('recommend', models.IntegerField(null=True)),
                ('time_shelves', models.DateField(null=True)),
                ('media_reviews', models.CharField(max_length=30, null=True)),
                ('directory', models.CharField(max_length=30, null=True)),
                ('author_profile', models.CharField(max_length=30, null=True)),
                ('content_intro', models.CharField(max_length=30, null=True)),
                ('edit_recom', models.CharField(max_length=100, null=True)),
                ('saves', models.FloatField(db_column='save', null=True)),
                ('ddpriice', models.FloatField(null=True)),
                ('pricing', models.FloatField(null=True)),
                ('packaging', models.CharField(max_length=20, null=True)),
                ('paper', models.CharField(max_length=20, null=True)),
                ('format', models.CharField(max_length=20, null=True)),
                ('pages', models.IntegerField(null=True)),
                ('words', models.IntegerField(null=True)),
                ('isbn', models.IntegerField(db_column='ISBN', null=True)),
                ('print_num', models.CharField(max_length=20, null=True)),
                ('printint_time', models.DateField(null=True)),
                ('edition', models.CharField(max_length=20, null=True)),
                ('publication_time', models.DateField(null=True)),
                ('press', models.CharField(max_length=30, null=True)),
                ('column_31', models.CharField(db_column='Column_31', max_length=10, null=True)),
                ('column_32', models.CharField(db_column='Column_32', max_length=10, null=True)),
                ('column_33', models.CharField(db_column='Column_33', max_length=10, null=True)),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='BookOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_count', models.IntegerField(null=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='show_app.Book')),
            ],
            options={
                'db_table': 'book_order',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20, null=True)),
                ('parent_id', models.IntegerField(null=True)),
                ('column_4', models.CharField(db_column='Column_4', max_length=10, null=True)),
                ('column_5', models.CharField(db_column='Column_5', max_length=10, null=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30, null=True)),
                ('user_name', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('status', models.BooleanField(default=False)),
                ('codes', models.CharField(max_length=40, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='YgBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.FloatField(null=True)),
                ('addr_name', models.CharField(max_length=30, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='show_app.Users')),
            ],
            options={
                'db_table': 'yg_book',
            },
        ),
        migrations.AddField(
            model_name='bookorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='show_app.YgBook'),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(db_column='category_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='show_app.Category'),
        ),
        migrations.AddField(
            model_name='addr',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='show_app.Users'),
        ),
    ]
